/**
 * Aura Frame API - Unofficial
 * Reverse Engineered API for Aura Frames
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dave@mudsite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ContributorTokens {
    'email'?: string;
    'phoneNumber'?: string;
    'expiresAt'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'frameId'?: string;
    'contributorName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phone_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "frameId",
            "baseName": "frame_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contributorName",
            "baseName": "contributor_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ContributorTokens.attributeTypeMap;
    }

    public constructor() {
    }
}

