/**
 * Aura Frame API - Unofficial
 * Reverse Engineered API for Aura Frames
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dave@mudsite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Asset } from '../models/Asset';
import { Metadata } from '../models/Metadata';
import { HttpFile } from '../http/http';

export class FeedItem {
    'assets'?: Array<Asset>;
    'metadata'?: Metadata;
    'message'?: string;
    'stickFor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assets",
            "baseName": "assets",
            "type": "Array<Asset>",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Metadata",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "stickFor",
            "baseName": "stick_for",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FeedItem.attributeTypeMap;
    }

    public constructor() {
    }
}

