/**
 * Aura Frame API - Unofficial
 * Reverse Engineered API for Aura Frames
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dave@mudsite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Frame } from '../models/Frame';
import { HttpFile } from '../http/http';

export class Frames {
    'frames'?: Array<Frame>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "frames",
            "baseName": "frames",
            "type": "Array<Frame>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Frames.attributeTypeMap;
    }

    public constructor() {
    }
}

