/**
 * Aura Frame API - Unofficial
 * Reverse Engineered API for Aura Frames
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dave@mudsite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Asset } from '../models/Asset';
import { ContributorTokens } from '../models/ContributorTokens';
import { FeedItem } from '../models/FeedItem';
import { FrameEnvironment } from '../models/FrameEnvironment';
import { Impression } from '../models/Impression';
import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class Frame {
    'id'?: string;
    'name'?: string;
    'userId'?: string;
    'softwareVersion'?: string;
    'buildVersion'?: string;
    'hwAndroidVersion'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'handledAt'?: string;
    'deletedAt'?: string;
    'updatedAtOnClient'?: string;
    'lastImpressionAt'?: string;
    'orientation'?: string;
    'autoBrightness'?: boolean;
    'minBrightness'?: string;
    'maxBrightness'?: string;
    'brightness'?: string;
    'senseMotion'?: boolean;
    'defaultSpeed'?: string;
    'slideshowInterval'?: string;
    'slideshowAuto'?: boolean;
    'digits'?: string;
    'contributorTokens'?: Array<ContributorTokens>;
    'hwSerial'?: string;
    'mattingColor'?: string;
    'trimColor'?: string;
    'isHandling'?: boolean;
    'calibrationsLastModifiedAt'?: string;
    'gesturesOn'?: boolean;
    'portraitPairingOff'?: string;
    'livePhotosOn'?: boolean;
    'autoProcessedPlaylistIds'?: Array<string>;
    'timeZone'?: string;
    'wifiNetwork'?: string;
    'coldBootAt'?: string;
    'isCharityWaterFrame'?: boolean;
    'numAssets'?: string;
    'thanksOn'?: boolean;
    'frameQueueUrl'?: string;
    'clientQueueUrl'?: string;
    'scheduledDisplaySleep'?: boolean;
    'scheduledDisplayOnAt'?: string;
    'scheduledDisplayOffAt'?: string;
    'forcedWifiState'?: string;
    'forcedWifiRecipientEmail'?: string;
    'isAnalogFrame'?: boolean;
    'controlType'?: string;
    'displayAspectRatio'?: string;
    'hasClaimableGift'?: boolean;
    'giftBillingHint'?: string;
    'locale'?: string;
    'frameType'?: string;
    'description'?: string;
    'representativeAssetId'?: string;
    'sortMode'?: string;
    'emailAddress'?: string;
    'features'?: Array<string>;
    'volume'?: string;
    'user'?: User;
    'playlists'?: Array<string>;
    'lastFeedItem'?: FeedItem;
    'lastImpression'?: Impression;
    'recentAssets'?: Array<Asset>;
    'contributors'?: Array<User>;
    'frameEnvironment'?: FrameEnvironment;
    'currentPrintSet'?: string;
    'firstPrintSet'?: string;
    'childAlbums'?: Array<string>;
    'smartAdds'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "user_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "softwareVersion",
            "baseName": "software_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildVersion",
            "baseName": "build_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "hwAndroidVersion",
            "baseName": "hw_android_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "handledAt",
            "baseName": "handled_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "deletedAt",
            "baseName": "deleted_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAtOnClient",
            "baseName": "updated_at_on_client",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastImpressionAt",
            "baseName": "last_impression_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "orientation",
            "baseName": "orientation",
            "type": "string",
            "format": ""
        },
        {
            "name": "autoBrightness",
            "baseName": "auto_brightness",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "minBrightness",
            "baseName": "min_brightness",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxBrightness",
            "baseName": "max_brightness",
            "type": "string",
            "format": ""
        },
        {
            "name": "brightness",
            "baseName": "brightness",
            "type": "string",
            "format": ""
        },
        {
            "name": "senseMotion",
            "baseName": "sense_motion",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "defaultSpeed",
            "baseName": "default_speed",
            "type": "string",
            "format": ""
        },
        {
            "name": "slideshowInterval",
            "baseName": "slideshow_interval",
            "type": "string",
            "format": ""
        },
        {
            "name": "slideshowAuto",
            "baseName": "slideshow_auto",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "digits",
            "baseName": "digits",
            "type": "string",
            "format": ""
        },
        {
            "name": "contributorTokens",
            "baseName": "contributor_tokens",
            "type": "Array<ContributorTokens>",
            "format": ""
        },
        {
            "name": "hwSerial",
            "baseName": "hw_serial",
            "type": "string",
            "format": ""
        },
        {
            "name": "mattingColor",
            "baseName": "matting_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "trimColor",
            "baseName": "trim_color",
            "type": "string",
            "format": ""
        },
        {
            "name": "isHandling",
            "baseName": "is_handling",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "calibrationsLastModifiedAt",
            "baseName": "calibrations_last_modified_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "gesturesOn",
            "baseName": "gestures_on",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "portraitPairingOff",
            "baseName": "portrait_pairing_off",
            "type": "string",
            "format": ""
        },
        {
            "name": "livePhotosOn",
            "baseName": "live_photos_on",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "autoProcessedPlaylistIds",
            "baseName": "auto_processed_playlist_ids",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "timeZone",
            "baseName": "time_zone",
            "type": "string",
            "format": ""
        },
        {
            "name": "wifiNetwork",
            "baseName": "wifi_network",
            "type": "string",
            "format": ""
        },
        {
            "name": "coldBootAt",
            "baseName": "cold_boot_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCharityWaterFrame",
            "baseName": "is_charity_water_frame",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "numAssets",
            "baseName": "num_assets",
            "type": "string",
            "format": ""
        },
        {
            "name": "thanksOn",
            "baseName": "thanks_on",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "frameQueueUrl",
            "baseName": "frame_queue_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "clientQueueUrl",
            "baseName": "client_queue_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduledDisplaySleep",
            "baseName": "scheduled_display_sleep",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "scheduledDisplayOnAt",
            "baseName": "scheduled_display_on_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "scheduledDisplayOffAt",
            "baseName": "scheduled_display_off_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "forcedWifiState",
            "baseName": "forced_wifi_state",
            "type": "string",
            "format": ""
        },
        {
            "name": "forcedWifiRecipientEmail",
            "baseName": "forced_wifi_recipient_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "isAnalogFrame",
            "baseName": "is_analog_frame",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "controlType",
            "baseName": "control_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayAspectRatio",
            "baseName": "display_aspect_ratio",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasClaimableGift",
            "baseName": "has_claimable_gift",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "giftBillingHint",
            "baseName": "gift_billing_hint",
            "type": "string",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "frameType",
            "baseName": "frame_type",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "representativeAssetId",
            "baseName": "representative_asset_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sortMode",
            "baseName": "sort_mode",
            "type": "string",
            "format": ""
        },
        {
            "name": "emailAddress",
            "baseName": "email_address",
            "type": "string",
            "format": ""
        },
        {
            "name": "features",
            "baseName": "features",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "volume",
            "baseName": "volume",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        },
        {
            "name": "playlists",
            "baseName": "playlists",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "lastFeedItem",
            "baseName": "last_feed_item",
            "type": "FeedItem",
            "format": ""
        },
        {
            "name": "lastImpression",
            "baseName": "last_impression",
            "type": "Impression",
            "format": ""
        },
        {
            "name": "recentAssets",
            "baseName": "recent_assets",
            "type": "Array<Asset>",
            "format": ""
        },
        {
            "name": "contributors",
            "baseName": "contributors",
            "type": "Array<User>",
            "format": ""
        },
        {
            "name": "frameEnvironment",
            "baseName": "frame_environment",
            "type": "FrameEnvironment",
            "format": ""
        },
        {
            "name": "currentPrintSet",
            "baseName": "current_print_set",
            "type": "string",
            "format": ""
        },
        {
            "name": "firstPrintSet",
            "baseName": "first_print_set",
            "type": "string",
            "format": ""
        },
        {
            "name": "childAlbums",
            "baseName": "child_albums",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "smartAdds",
            "baseName": "smart_adds",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Frame.attributeTypeMap;
    }

    public constructor() {
    }
}

