/**
 * Aura Frame API - Unofficial
 * Reverse Engineered API for Aura Frames
 *
 * OpenAPI spec version: 0.0.1
 * Contact: dave@mudsite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class User {
    'id'?: string;
    'shortId'?: string;
    'testAccount'?: string;
    'createdAt'?: string;
    'updatedAt'?: string;
    'latestAppVersion'?: string;
    'name'?: string;
    'email'?: string;
    'attributionId'?: string;
    'attributionString'?: string;
    'showPushPrompt'?: boolean;
    'avatarFileName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "shortId",
            "baseName": "short_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "testAccount",
            "baseName": "test_account",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "latestAppVersion",
            "baseName": "latest_app_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributionId",
            "baseName": "attribution_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributionString",
            "baseName": "attribution_string",
            "type": "string",
            "format": ""
        },
        {
            "name": "showPushPrompt",
            "baseName": "show_push_prompt",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "avatarFileName",
            "baseName": "avatar_file_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }

    public constructor() {
    }
}

